GEM-48 | Add update group attachments
Group-Expense-Manager/attachment-store pull request #6
Opened 2024-07-06 21:56 UTC by lawos98

2024-07-07 09:20 UTC, pwgacek requested changes

2024-07-07 09:20 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/external/controller/ExternalGroupController.kt
> +    ): GroupAttachmentResponse {
should update endpoint return attachmentId even though it never changes? (Just asking meybe i am wrong)

2024-07-07 09:20 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/service/GroupService.kt
> +    fun updateAttachment(data: ByteArray, attachmentId: String, groupId: String, userId: String): GroupAttachment {
shouldn't we allow only Attachment author to change it? If i am not mistaken we've got only two possible scenarios for adding new group attachment: groupImage & expenseAttachment. I think we should allow only group creator to change image (as only group creator can change group name). Same case for expense attachment.

2024-07-07 09:20 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/service/GroupService.kt
> +    fun updateAttachment(data: ByteArray, attachmentId: String, groupId: String, userId: String): GroupAttachment {
Will reports be stored in attachment store? If yes, i don't think we should allow to change them.

2024-07-07 09:20 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/service/GroupService.kt
> +    fun updateAttachment(data: ByteArray, attachmentId: String, groupId: String, userId: String): GroupAttachment {
what if somebody would try to update image with for example csv report

2024-07-07 09:20 UTC, pwgacek commented on src/integration/kotlin/pl/edu/agh/gem/integration/ability/ServiceTestClient.kt
> +            .uri(URI("/external/groups/$groupId/attachments/$attachmentId"))
please use EXTERNAL constant

2024-07-09 18:49 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/external/controller/ExternalGroupController.kt
> +    ): GroupAttachmentResponse {
for my POV we should return the same dto like when we create new attachemnts soo i added that, but now we retrive only id.

2024-07-09 19:03 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/internal/service/GroupService.kt
> +    fun updateAttachment(data: ByteArray, attachmentId: String, groupId: String, userId: String): GroupAttachment {
i dont sure if we want to set that only creator of group can change that  photo or name of group. I added flat to chose what option we want to have

2024-07-09 19:08 UTC, lawos98 commented on src/integration/kotlin/pl/edu/agh/gem/integration/ability/ServiceTestClient.kt
> +            .uri(URI("/external/groups/$groupId/attachments/$attachmentId"))
changed

2024-07-10 04:23 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/external/controller/ExternalGroupController.kt
> +    ): GroupAttachmentResponse {
ok

2024-07-10 04:24 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/service/GroupService.kt
> +    fun updateAttachment(data: ByteArray, attachmentId: String, groupId: String, userId: String): GroupAttachment {
will discuss on daily

2024-07-10 17:40 UTC, pwgacek approved these changes

2024-07-10 17:46 UTC, merged