GEM-43 | Add all variants for user attachments
Group-Expense-Manager/attachment-store pull request #7
Opened 2024-07-06 21:56 UTC by lawos98

2024-07-07 10:16 UTC, pwgacek requested changes

2024-07-07 10:16 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/external/controller/user/ExternalUserController.kt
> +@RequestMapping("/external/users/")
EXTERNAL

2024-07-07 10:16 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/external/controller/user/InternalUserController.kt
> +@RequestMapping("/internal/users")
INTERNAL

2024-07-07 10:16 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/service/UserService.kt
> +        val generateImage = fileLoader.loadRandomGroupImage()
```suggestion
        val generateImage = fileLoader.loadRandomUserImage()
```

2024-07-07 10:16 UTC, pwgacek commented on src/integration/kotlin/pl/edu/agh/gem/integration/controler/user/InternalUserControllerIT.kt
> +        val groupId = GROUP_ID
unused variable

2024-07-07 10:16 UTC, pwgacek commented on src/integration/kotlin/pl/edu/agh/gem/integration/mapper/AttachmentMapperIT.kt
> +    should("map UserAttachmentt to ResponseEntity") {
typo

2024-07-07 10:16 UTC, pwgacek commented on src/test/kotlin/pl/edu/agh/gem/external/persistence/UserAttachmentEntityTest.kt
> +import pl.edu.agh.gem.external.persistence.group.toDomain
unused import, same in 6th line

2024-07-07 10:16 UTC, pwgacek commented on src/test/kotlin/pl/edu/agh/gem/external/persistence/UserAttachmentEntityTest.kt
> +    should("map correct UserAttachmentEntity to UserAttachment") {
```suggestion
    should("map correct UserAttachment to UserAttachmentEntity") {
```

2024-07-07 10:16 UTC, pwgacek commented on src/test/kotlin/pl/edu/agh/gem/external/persistence/UserAttachmentEntityTest.kt
> +    should("map correct UserAttachment to UserAttachmentEntity") {
```suggestion
    should("map correct UserAttachmentEntity to UserAttachment") {
```

2024-07-07 10:16 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/internal/persistence/UserAttachmentRepository.kt
> +    "Attachment with id:$attachmentId for userId:$userId not found",
```suggestion
    "Attachment with id: $attachmentId for userId: $userId not found",
```

2024-07-07 10:16 UTC, pwgacek commented on src/integration/kotlin/pl/edu/agh/gem/integration/controler/user/ExternalUserControllerIT.kt
> +        val groupMembers = createGroupMembersResponse(user.id)
not used

2024-07-07 10:18 UTC, pwgacek commented
Pytanie czy nie chcemy zrobić zeby użytkownik mógł miec max 1 obrazek

2024-07-09 19:58 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/external/controller/user/ExternalUserController.kt
> +@RequestMapping("/external/users/")
changed

2024-07-09 19:58 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/external/controller/user/InternalUserController.kt
> +@RequestMapping("/internal/users")
changed

2024-07-09 19:59 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/internal/service/UserService.kt
> +        val generateImage = fileLoader.loadRandomGroupImage()
changed

2024-07-09 19:59 UTC, lawos98 commented on src/integration/kotlin/pl/edu/agh/gem/integration/controler/user/InternalUserControllerIT.kt
> +        val groupId = GROUP_ID
removed

2024-07-09 20:00 UTC, lawos98 commented on src/integration/kotlin/pl/edu/agh/gem/integration/mapper/AttachmentMapperIT.kt
> +    should("map UserAttachmentt to ResponseEntity") {
fixed

2024-07-09 20:03 UTC, lawos98 commented on src/test/kotlin/pl/edu/agh/gem/external/persistence/UserAttachmentEntityTest.kt
> +import pl.edu.agh.gem.external.persistence.group.toDomain
hmmm, interesting why detect and ktlint dont check that

2024-07-09 20:04 UTC, lawos98 commented on src/test/kotlin/pl/edu/agh/gem/external/persistence/UserAttachmentEntityTest.kt
> +    should("map correct UserAttachmentEntity to UserAttachment") {
fixed

2024-07-09 20:04 UTC, lawos98 commented on src/test/kotlin/pl/edu/agh/gem/external/persistence/UserAttachmentEntityTest.kt
> +    should("map correct UserAttachment to UserAttachmentEntity") {
fixed

2024-07-09 20:05 UTC, lawos98 commented on src/main/kotlin/pl/edu/agh/gem/internal/persistence/UserAttachmentRepository.kt
> +    "Attachment with id:$attachmentId for userId:$userId not found",
changed

2024-07-09 20:07 UTC, lawos98 commented
Pytanie czy nie chcemy zrobić zeby użytkownik mógł miec max 1 obrazek

Raczej bym nie dodawał takiego ograniczenia, nie widzę jakieś korzysci z takiego ograniczenia a moga pojawić się ewentaulne problemu się powiększają

2024-07-10 04:40 UTC, pwgacek requested changes

2024-07-10 04:40 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/external/controller/user/ExternalUserController.kt
> +@RequestMapping("/external/users/")
not changed

2024-07-10 04:40 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/external/controller/user/InternalUserController.kt
> +@RequestMapping("/internal/users")
not changed

2024-07-10 17:44 UTC, pwgacek approved these changes

2024-07-10 19:09 UTC, merged